project:
  type: book

book:
  title: "ccstwin"
  author: "Jerell James"
  public-url: https://jerell.me/ccstwin/
  repo-url: https://github.com/Jerell/ccstwin
  repo-actions: [edit, issue]
  reader-mode: true
  downloads: [pdf, epub]

  chapters:
    - index.qmd
    - part: Modelling
      chapters:
        - networkcomposition.qmd
        - whatif.qmd
        - solving.qmd
    - fluidproperties.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    html-math-method: katex
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto

crossref:
  eq-prefix: Eq
